services:
  # PressHost
  presshost:
    image: ghcr.io/butialabs/presshost:latest
    container_name: presshost
    restart: unless-stopped
    environment:
      SITEURL: https://your-domain.xyz
      DB_NAME: presshost
      DB_USER: presshost
      DB_PASSWORD: p@ssw0rd
      DB_HOST: db
      TZ: UTC
    volumes:
      - ./presshost/press:/site/press
      - ./presshost/uploads:/site/uploads
      - ./presshost/cache:/site/cache
      - ./presshost/logs:/site/logs
      - ./presshost/ssl:/site/ssl # or if use certbot ./presshost/certbot:/site/ssl
    networks:
      - presshost
    ports:
      - 80:80
      - 443:443
    depends_on:
      - db
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"

  # Database
  db:
    image: mariadb:11
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: p@ssw0rd
      MYSQL_DATABASE: presshost
      MYSQL_USER: presshost
      MYSQL_PASSWORD: p@ssw0rd
    volumes:
      - ./presshost/db/data:/var/lib/mysql
    networks:
      - presshost
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"

networks:
  presshost:
    name: presshost
