services:
  # PressHost
  presshost:
    image: ghcr.io/butialabs/presshost:latest
    container_name: presshost
    restart: unless-stopped
    environment:
      SITE_URL: your-domain.xyz
      DB_NAME: presshost
      DB_USER: presshost
      DB_PASSWORD: p@ssw0rd
      DB_HOST: db
      WP_SITEURL: https://${SITE_URL}
      WP_HOME: https://${SITE_URL}
      TZ: UTC

      # SSL_CERT_PATH: /site/ssl/live/${SITE_URL}/fullchain.pem
      # SSL_PRIVATE_PATH: /site/ssl/live/${SITE_URL}/privkey.pem
      # SSL_TRUSTED_CERT_PATH: /site/ssl/live/${SITE_URL}/chain.pem
      # NGINX_SSL_STAPLING: "on"
      # NGINX_SSL_STAPLING_VERIFY: "on"
    volumes:
      - /opt/press:/site/press
      - /opt/uploads:/site/uploads
      - /opt/cache:/site/cache
      - /opt/logs:/site/logs
      # - /opt/certbot:/site/ssl
    networks:
      - presshost
    ports:
      - 80:80
      - 443:443
    depends_on:
      - db
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"

  # Database
  db:
    image: mariadb:11
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: p@ssw0rd
      MYSQL_DATABASE: presshost
      MYSQL_USER: presshost
      MYSQL_PASSWORD: p@ssw0rd
    volumes:
      - /opt/presshost/db/data:/var/lib/mysql
    networks:
      - presshost
    ports:
      - 3306:3306
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"

  # SSL
  certbot:
    image: git.mrmeeb.stream/mrmeeb/certbot-cron:latest
    container_name: certbot
    restart: unless-stopped
    volumes:
      - /opt/certbot:/config
    environment:
      - EMAIL: tecnologia@${SITE_URL}
      - DOMAINS: ${SITE_URL},www.${SITE_URL}
      - PLUGIN: cloudflare
      - CLOUDFLARE_TOKEN: null

networks:
  presshost:
    name: presshost