location ~ /purge(/.*) {
    allow 127.0.0.1;
    allow 10.0.0.0/8;
    allow 172.16.0.0/12;
    allow 192.168.0.0/16;
    deny all;

    fastcgi_cache_purge PRESSHOST "$scheme$request_method$host$1$is_mobile$is_logged_in";
}
