try_files                     $fastcgi_script_name =404;

include                       fastcgi_params;

fastcgi_index                 index.php;
fastcgi_buffers               16 16k;
fastcgi_buffer_size           32k;

fastcgi_param PATH_INFO       $fastcgi_path_info;
fastcgi_param DOCUMENT_ROOT   $realpath_root;
fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
fastcgi_param PHP_ADMIN_VALUE "open_basedir=$base/:/usr/lib/php/:/tmp/";

fastcgi_keep_conn on;
