try_files                     $fastcgi_script_name =404;

include                       fastcgi_params;

fastcgi_param HTTP_HOST       $http_host;

fastcgi_index                 index.php;

fastcgi_param PATH_INFO       $fastcgi_path_info;
fastcgi_param DOCUMENT_ROOT   $realpath_root;
fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
fastcgi_param PHP_ADMIN_VALUE "open_basedir=$base/:/usr/lib/php/:/tmp/";

fastcgi_param NGINX_VERSION   $nginx_version;

fastcgi_param HTTPS           $real_https if_not_empty;
fastcgi_param REQUEST_SCHEME  $real_scheme;
fastcgi_param HTTP_AUTHORIZATION $http_authorization;

fastcgi_keep_conn on;
