location = /wp-includes/js/tinymce/wp-tinymce.php {
    include conf.d/fastcgi.conf;
}

location ~* ^/(?:wp-content|wp-includes)/.*\.php$ {
    deny all;
}

location ~* ^/wp-content/uploads/.*\.(?:s?html?|php|js|swf)$ {
    deny all;
}

location ~* ^/wp-content/plugins/wordpress-seo(?:-premium)?/css/main-sitemap\.xsl$ {}

location ~ ^/wp-content/plugins {
    deny all;
}

location ~* ^/(?:xmlrpc\.php|wp-links-opml\.php|wp-config\.php|wp-config-sample\.php|readme\.html|license\.txt)$ {
    deny all;
}

location ~\.(ini|log|conf|sql|bak|backup|old|orig|tmp|temp|swp|swo)$ {
    deny all;
}

location ~* /(?:uploads|files)/.*\.php$ {
    deny all;
}

location ~* /(debug\.log|error_log|wp-errors\.log) {
    deny all;
}

location ~ ^/(wp-admin|wp-login\.php) {
    fastcgi_cache_bypass 1;
    fastcgi_no_cache 1;

    fastcgi_pass unix:/var/run/php/php-fpm.sock;
    include conf.d/fastcgi.conf;
}

location ~ ^/wp-json/ {
    fastcgi_pass unix:/var/run/php/php-fpm.sock;
    include conf.d/fastcgi.conf;
    include conf.d/cache-fastcgi.conf;
}

location = /wp-cron.php {
    allow 127.0.0.1;
    allow 10.0.0.0/8;
    allow 172.16.0.0/12;
    allow 192.168.0.0/16;
    deny all;
    fastcgi_pass unix:/var/run/php/php-fpm.sock;
    include conf.d/fastcgi.conf;
}