set $real_scheme $scheme;
if ($http_x_forwarded_proto != "") {
    set $real_scheme $http_x_forwarded_proto;
}

set $real_host $host;
if ($http_x_forwarded_host != "") {
    set $real_host $http_x_forwarded_host;
}

set_real_ip_from 10.0.0.0/8;
set_real_ip_from 172.16.0.0/12;
set_real_ip_from 192.168.0.0/16;
set_real_ip_from fc00::/7;
set_real_ip_from 127.0.0.0/8;
set_real_ip_from ::1/128;

real_ip_header X-Forwarded-For;
real_ip_recursive on;
