location = /favicon.ico {
    access_log off;
    limit_req off;
    limit_conn off;
}

location = /robots.txt {
    access_log off;
    limit_req off;
    limit_conn off;
}

location ~* \.(?:css(\.map)?|js(\.map)?|jpe?g|png|gif|ico|cur|heic|webp|tiff?|mp3|m4a|aac|ogg|midi?|wav|mp4|mov|webm|mpe?g|avi|ogv|flv|wmv)$ {
    expires 365d;
    access_log off;
    add_header Cache-Control "public, immutable";
    limit_req off;
    limit_conn off;
}

location ~* \.(?:svgz?|ttf|ttc|otf|eot|woff2?)$ {
    add_header Access-Control-Allow-Origin "*";
    expires 365d;
    limit_req off;
    limit_conn off;
}