# Valkey — local object cache server (generated by presshost-init)
bind ${VALKEY_BIND} -::1
port ${VALKEY_PORT}
protected-mode yes

daemonize no
supervised no

dir /run/valkey
${VALKEY_SAVE_LINE}

maxmemory ${VALKEY_MAXMEMORY}
maxmemory-policy ${VALKEY_MAXMEMORY_POLICY}

logfile ""

${VALKEY_REQUIREPASS_LINE}
