services:
  app:
    image: ghcr.io/butialabs/presshost:latest
    container_name: app
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443/udp
      - 443:443/tcp
    env_file:
      - .env
    volumes:
      # WordPress/ClassicPress files
      - /opt/press:/site/press
      - /opt/uploads:/site/uploads
      # Cache directory for disk-based cache plugins
      - /opt/cache:/site/cache
      # SSL certificates
      - /opt/certbot/etc:/etc/letsencrypt:ro
      - /opt/certbot/webroot:/var/www/certbot:ro
      - /opt/certbot/certs:/etc/ssl/certs:ro
      # Logs
      - /opt/logs:/var/log
    networks:
      - presshost
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
        
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 6379:6379
    volumes:
      - /opt/redis/data:/data
      - /opt/logs/redis:/var/log/redis
    command: >
      sh -c "redis-server
      --requirepass $${REDIS_PASSWORD}
      --appendonly yes
      --appendfsync everysec
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru"
    networks:
      - presshost
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
        
  mariadb:
    image: mariadb:11
    container_name: mariadb
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - /opt/mariadb/data:/var/lib/mysql
      - /opt/logs/mariadb:/var/log/mariadb
    networks:
      - presshost
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"

networks:
  presshost:
    name: presshost